// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PersonService.proto

package personService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Classes, Types //===========================================================|
type PhoneType int32

const (
	PhoneType_NONE       PhoneType = 0
	PhoneType_STATIONARY PhoneType = 1
	PhoneType_CELLULAR   PhoneType = 2
	PhoneType_OTHER      PhoneType = 3
)

var PhoneType_name = map[int32]string{
	0: "NONE",
	1: "STATIONARY",
	2: "CELLULAR",
	3: "OTHER",
}

var PhoneType_value = map[string]int32{
	"NONE":       0,
	"STATIONARY": 1,
	"CELLULAR":   2,
	"OTHER":      3,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b8af27ab26eb93f, []int{0}
}

// Requests //=================================================================|
type GetPersonRequest struct {
	PersonId             int32    `protobuf:"varint,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonRequest) Reset()         { *m = GetPersonRequest{} }
func (m *GetPersonRequest) String() string { return proto.CompactTextString(m) }
func (*GetPersonRequest) ProtoMessage()    {}
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b8af27ab26eb93f, []int{0}
}

func (m *GetPersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonRequest.Unmarshal(m, b)
}
func (m *GetPersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonRequest.Marshal(b, m, deterministic)
}
func (m *GetPersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonRequest.Merge(m, src)
}
func (m *GetPersonRequest) XXX_Size() int {
	return xxx_messageInfo_GetPersonRequest.Size(m)
}
func (m *GetPersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonRequest proto.InternalMessageInfo

func (m *GetPersonRequest) GetPersonId() int32 {
	if m != nil {
		return m.PersonId
	}
	return 0
}

// Responses //================================================================|
type GetPersonResponse struct {
	Persons              []*Person `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPersonResponse) Reset()         { *m = GetPersonResponse{} }
func (m *GetPersonResponse) String() string { return proto.CompactTextString(m) }
func (*GetPersonResponse) ProtoMessage()    {}
func (*GetPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b8af27ab26eb93f, []int{1}
}

func (m *GetPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonResponse.Unmarshal(m, b)
}
func (m *GetPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonResponse.Marshal(b, m, deterministic)
}
func (m *GetPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonResponse.Merge(m, src)
}
func (m *GetPersonResponse) XXX_Size() int {
	return xxx_messageInfo_GetPersonResponse.Size(m)
}
func (m *GetPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonResponse proto.InternalMessageInfo

func (m *GetPersonResponse) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

type Phone struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=personService.PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Phone) Reset()         { *m = Phone{} }
func (m *Phone) String() string { return proto.CompactTextString(m) }
func (*Phone) ProtoMessage()    {}
func (*Phone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b8af27ab26eb93f, []int{2}
}

func (m *Phone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phone.Unmarshal(m, b)
}
func (m *Phone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phone.Marshal(b, m, deterministic)
}
func (m *Phone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phone.Merge(m, src)
}
func (m *Phone) XXX_Size() int {
	return xxx_messageInfo_Phone.Size(m)
}
func (m *Phone) XXX_DiscardUnknown() {
	xxx_messageInfo_Phone.DiscardUnknown(m)
}

var xxx_messageInfo_Phone proto.InternalMessageInfo

func (m *Phone) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Phone) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_NONE
}

type Person struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phones               []*Phone `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b8af27ab26eb93f, []int{3}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetPhones() []*Phone {
	if m != nil {
		return m.Phones
	}
	return nil
}

func init() {
	proto.RegisterEnum("personService.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*GetPersonRequest)(nil), "personService.GetPersonRequest")
	proto.RegisterType((*GetPersonResponse)(nil), "personService.GetPersonResponse")
	proto.RegisterType((*Phone)(nil), "personService.Phone")
	proto.RegisterType((*Person)(nil), "personService.Person")
}

func init() { proto.RegisterFile("PersonService.proto", fileDescriptor_1b8af27ab26eb93f) }

var fileDescriptor_1b8af27ab26eb93f = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0x87, 0x0b, 0x6d, 0x79, 0xbb, 0xf3, 0xda, 0x06, 0xc7, 0x3f, 0x21, 0x7a, 0x90, 0x70, 0x22,
	0xa6, 0xa1, 0x09, 0xde, 0x4d, 0x88, 0x12, 0x6d, 0x82, 0x40, 0xb6, 0x78, 0xd0, 0x8b, 0x69, 0x65,
	0x13, 0x39, 0x14, 0x56, 0x96, 0x9a, 0xf4, 0xdb, 0x9b, 0xb2, 0x48, 0x5a, 0xa2, 0xb7, 0xdd, 0xc9,
	0x33, 0xbf, 0x67, 0x32, 0x03, 0x27, 0x31, 0x2b, 0x45, 0x91, 0x2f, 0x58, 0xf9, 0x95, 0xbd, 0x33,
	0x87, 0x97, 0x45, 0x55, 0xe0, 0x98, 0xef, 0x17, 0xad, 0x19, 0xe8, 0x0f, 0xac, 0x92, 0x20, 0x65,
	0x9f, 0x1b, 0x26, 0x2a, 0xbc, 0x04, 0x22, 0xa1, 0xb7, 0x2c, 0x35, 0x14, 0x53, 0xb1, 0x87, 0x74,
	0x24, 0x0b, 0xf3, 0xd4, 0xba, 0x87, 0xe3, 0xbd, 0x06, 0xc1, 0x8b, 0x5c, 0x30, 0x9c, 0xc1, 0x3f,
	0x09, 0x08, 0x43, 0x31, 0xfb, 0xf6, 0x7f, 0xf7, 0xcc, 0x39, 0xd0, 0x38, 0x0d, 0xff, 0x43, 0x59,
	0x4f, 0x30, 0x8c, 0x3f, 0x8a, 0x9c, 0xe1, 0x39, 0x68, 0xf9, 0x66, 0xbd, 0x62, 0x65, 0x2d, 0x22,
	0xb4, 0xf9, 0xe1, 0x14, 0x06, 0xd5, 0x96, 0x33, 0x43, 0x35, 0x15, 0x7b, 0xe2, 0x1a, 0xdd, 0xb8,
	0x5d, 0x6f, 0xb2, 0xe5, 0x8c, 0xd6, 0x94, 0xf5, 0x0a, 0x9a, 0x34, 0xe0, 0x04, 0xd4, 0x76, 0x68,
	0x35, 0x4b, 0x11, 0x61, 0x90, 0x2f, 0xd7, 0x32, 0x87, 0xd0, 0xfa, 0x8d, 0x53, 0xd0, 0xf8, 0x2e,
	0x40, 0x18, 0xfd, 0x7a, 0xd8, 0xd3, 0xdf, 0xd2, 0x69, 0xc3, 0x5c, 0xdf, 0x02, 0x69, 0x75, 0x38,
	0x82, 0x41, 0x18, 0x85, 0xbe, 0xde, 0xc3, 0x09, 0xc0, 0x22, 0xf1, 0x92, 0x79, 0x14, 0x7a, 0xf4,
	0x45, 0x57, 0xf0, 0x08, 0x46, 0x77, 0x7e, 0x10, 0x3c, 0x07, 0x1e, 0xd5, 0x55, 0x24, 0x30, 0x8c,
	0x92, 0x47, 0x9f, 0xea, 0x7d, 0x77, 0x09, 0xe3, 0x83, 0x3b, 0x60, 0x0c, 0xa4, 0xdd, 0x20, 0x5e,
	0x75, 0xdc, 0xdd, 0x63, 0x5c, 0x98, 0x7f, 0x03, 0x72, 0xf9, 0x56, 0x6f, 0xa5, 0xd5, 0xa7, 0xbd,
	0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xc8, 0xeb, 0xf4, 0xf1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonServiceClient is the client API for PersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonServiceClient interface {
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := c.cc.Invoke(ctx, "/personService.PersonService/GetPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServiceServer is the server API for PersonService service.
type PersonServiceServer interface {
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
}

// UnimplementedPersonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPersonServiceServer struct {
}

func (*UnimplementedPersonServiceServer) GetPerson(ctx context.Context, req *GetPersonRequest) (*GetPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personService.PersonService/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personService.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _PersonService_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PersonService.proto",
}
